apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-pipelines-agent
  labels:
    app.kubernetes.io/name: azure-pipelines-agent
    app.kubernetes.io/instance: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-pipelines-agent
      app.kubernetes.io/instance: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-pipelines-agent
        app.kubernetes.io/instance: agent
    spec:
      imagePullSecrets:
        - name: YourImagePullTokenSecretIfPrivate ######### UPDATE THIS VALUE IF PRIVATE IMAGE REGISTRY, OTHERWISE DELETE ####
      containers:
        - name: azure-pipelines-agent
          image: <YourImageRegistryURL.com:v1> ############ UPDATE THIS VALUE ###################
          imagePullPolicy: Always
          env:
            - name: AZP_AGENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: AZP_URL
              valueFrom: 
                secretKeyRef:
                  key: AZP_URL
                  name: azure-pipelines-agent-secret
            - name: AZP_POOL
              valueFrom: 
                secretKeyRef:
                  key: AZP_POOL
                  name: azure-pipelines-agent-secret
            - name: AZP_TOKEN
              valueFrom: 
                secretKeyRef:
                  key: AZP_TOKEN
                  name: azure-pipelines-agent-secret
            - name: AZP_AGENT_NAME
              valueFrom: 
                secretKeyRef:
                  key: AZP_AGENT_NAME
                  name: azure-pipelines-agent-secret